#!/bin/bash
# Generated by GitGraph Architect
#
# INSTRUCTIONS:
# 1. Save this file as 'generate_graph.sh'
# 2. Run 'chmod +x generate_graph.sh'
# 3. Run './generate_graph.sh'
# 4. Follow the final instructions to push to GitHub

REPO_NAME="my-contribution-graph"

# --- Configuration ---
GIT_USER_NAME="Ruchita Lawand"
GIT_USER_EMAIL="ruchitalawand@gmail.com"

echo "Initializing repository: $REPO_NAME"

mkdir -p "$REPO_NAME"
cd "$REPO_NAME"

# Initialize git
git init -b main

# Configure local git user to ensure contributions are attributed correctly
git config user.name "$GIT_USER_NAME"
git config user.email "$GIT_USER_EMAIL"

echo "User configured as: $GIT_USER_NAME <$GIT_USER_EMAIL>"
echo "Creating contribution pattern..."

# Create a README to avoid an empty repo warning
echo "# My Contribution Graph" > README.md
echo "Generated with GitGraph Architect" >> README.md
git add README.md
git commit -m "Initial commit"


echo "------------------------------------------------"
echo "Generation Complete!"
echo "Created 0 active days with contributions."
echo ""
echo "NEXT STEPS:"
echo "1. Create a new repository on GitHub (do not initialize with README/license)"
echo "2. Run the following commands:"
echo ""
echo "   cd $REPO_NAME"
echo "   git remote add origin https://github.com/<YOUR_USERNAME>/$REPO_NAME.git"
echo "   git push -u origin main"
echo ""
